### ISSUE TITLE
1.6.16 backport candidates

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/backport#2]
```
git log --oneline --pretty="format:%m https://github.com/nim-lang/Nim/commit/%H %s" --left-right  --cherry-pick devel...origin/version-1-6
```

2023-09-11T08:15:53+02:00

* [ ] ~~https://github.com/nim-lang/Nim/commit/fbb5ac512cd03a67a3364469132a881341e10e1c Remove some unnecessary initialization in `seq` operations (#22677)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/8853fb07753756dbe29364e8a32081462367215d Make `newSeqOfCap` not initialize memory. (#21842)~~
* [x] https://github.com/nim-lang/Nim/commit/ee4a219012ca1fcb2cfb2cce4e87ff6774009d86 Fix #17509: Continue instead of return with unfinished generics (#22563)
* [x] https://github.com/nim-lang/Nim/commit/a4df44d9fbe3328b2dd3b7209b98f80fdd5d361a Remove some unnecessary initialization in string operations (#22579)
* [x] https://github.com/nim-lang/Nim/commit/d2f36c071b1967e864961f423596d3931e84e49b Exclude block from endsInNoReturn, fix regression (#22632)
* [x] https://github.com/nim-lang/Nim/commit/2542dc09c829a709050335066b0f414d6fc68fe2 use dummy dest for void branches to fix noreturn in VM (#22617)
* [x] https://github.com/nim-lang/Nim/commit/6738f44af3866e4cace94d34b653acf3283f0cde unify explicit generic param semchecking in calls (#22618)
* [ ] ~~https://github.com/nim-lang/Nim/commit/0c6e13806d0abfad30b8a4bd9f1fe7858ff2125a fixes internal error: no generic body fixes #1500 (#22580)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/f1789cc465bcabc7afe0fe991df615246cfadb3b resolve local symbols in generic type call RHS (#22610)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/53d9fb259fc7d36660be20be0a199625ef126376 don't update const symbol on const section re-sems (#22609)~~
* [x] https://github.com/nim-lang/Nim/commit/3b206ed988765419c5ff02c2b08645f24ed0cbad Fix #22604: Make endsInNoReturn traverse the tree (#22612)
* [x] https://github.com/nim-lang/Nim/commit/5bd1afc3f9716fed833b7bd251ee45479b78a950 fixes #17197; fixes #22560; fixes the dest of newSeqOfCap in refc (#22594)
* [x] https://github.com/nim-lang/Nim/commit/2e4e2f8f5076b39e5976ba20f231f468b1b5052c handle typedesc params in VM (#22581)
* [x] https://github.com/nim-lang/Nim/commit/b6cea7b599b81db675b95d2f84a8e3cda071cb0d clearer error for different size int/float cast in VM (#22582)
* [x] https://github.com/nim-lang/Nim/commit/3de8d755135d94983ca087f448ad76832c341eaa correct logic for qualified symbol in templates (#22577)
* [x] https://github.com/nim-lang/Nim/commit/94454addb2a045731f2b4f44d697a319e3a20071 define toList procs after add for lists [backport] (#22573)
* [x] https://github.com/nim-lang/Nim/commit/2e7c8a339f654ebd6fe178f4c81aa89c14851f22 newStringOfCap now won't initialize all elements anymore (#22568)
* [x] https://github.com/nim-lang/Nim/commit/0b78b7f595ef96a9769e0d59167239c611b9857a fix #22548;environment misses for type reference in iterator access n… (#22559)
* [ ] https://github.com/nim-lang/Nim/commit/bc9785c08d53c2f94f62738e541508592c9b3b24 Fix `getAppFilename` exception handling (#22544)
* [x] https://github.com/nim-lang/Nim/commit/c56a712e7d54485b97df3b110ef148f5c12f2ab3 fixes #22541; peg matchLen can raise an unlisted exception: Exception (#22545)
* [x] https://github.com/nim-lang/Nim/commit/3de75ffc02ea85b95702ec0dc0976748954d3e2c Fix #21532: Check if template return is untyped (#22517)
* [x] https://github.com/nim-lang/Nim/commit/942f846f04b4fa3c3154f7277ab1a8f6762d2714 fix getNullValue for cstring in VM, make other VM code aware of nil cstring (#22527)
* [ ] ~~https://github.com/nim-lang/Nim/commit/20cbdc2741e9e34a99288ded9664378afc80acb6 Fix #22366 by making nimlf_/nimln_ part of the same line  (#22503)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/299394d21a3b7f2af02c8cdede1dcd0cd5948a0e Fix `seq.capacity` (#22488)~~
* [x] https://github.com/nim-lang/Nim/commit/ade75a148332e670244a719202f7f0337d2e469a fixes #22481; fixes `card` undefined misalignment behavior (#22484)
* [x] https://github.com/nim-lang/Nim/commit/6c4e7835bf9c1fea608c1f9f55026095fcdd14b2 When in object handles procedure call again, fixes #22474 (#22480)
* [x] https://github.com/nim-lang/Nim/commit/1927ae72d093d5e13bef6fd3fdf4700aa072f6bc Add Linux constant SO_BINDTODEVICE (#22468)
* [x] https://github.com/nim-lang/Nim/commit/9207d77848d6f5db3635ae64f3cd4972cdbe3296 fixes bareExcept warnings; catch specific exceptions (#21119)
* [ ] ~~https://github.com/nim-lang/Nim/commit/3f7e1d7daadf4002da1a155d7b98ff7fcca9e2fa replace `doAssert false` with `raiseAssert` in lib, which works better with strictdefs (#22458)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/faf1c91e6a418e21d56ac6e45e1dbc851f9ffd22 fixes move sideeffects issues [backport] (#22439)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/7be2e2bef545e68ac3d88876fe7073a033fbb5f4 replaces `doAssert false` with `raiseAssert` for unreachable branches, which works better with strictdefs (#22436)~~
* [x] https://github.com/nim-lang/Nim/commit/46e94c83d451895ead4f51686f614d8c9b1e384c Fix #5780 (#22428)
* [ ] ~~https://github.com/nim-lang/Nim/commit/db435a4a797adbbd4dd42edf89267902c0b2e34f Fix searchExtPos so that it returns -1 when the path is not a file ext (#22245)~~
* [x] https://github.com/nim-lang/Nim/commit/3efabd3ec669914ad2bb42a614f7277caf662562 Fix crash when using uninstantiated generic (#22379)
* [ ] ~~https://github.com/nim-lang/Nim/commit/f3a7622514f24740c6b33f0c37ebe6339ad5b70d fixes #22360; compare with the half of randMax (#22361)~~
* [x] https://github.com/nim-lang/Nim/commit/a23e53b4902d227353886d97ef50609709519dd9 fixes #22262; fixes `-d:useMalloc` broken with `--mm:none` and `--threads on` (#22355)
* [x] https://github.com/nim-lang/Nim/commit/f1ac979184ad7fa0d8c44415e781181a00a0095f Remove declared and not used variable in packedsets.bitincl (#22334)
* [x] https://github.com/nim-lang/Nim/commit/8216d7dd4635db3c0566155c35bb6f339daedbe3 fixes #22321; fixes building DLL with --noMain still produces a DllMain (#22323)
* [x] https://github.com/nim-lang/Nim/commit/62869a5c68e4dd91e00ee77b039f0175482ef4fa Check try block for endsInNoReturn (#22314)
* [x] https://github.com/nim-lang/Nim/commit/3ebe24977ce93ca3c347550c69dbfa7c9a7db507 Open scope for defer (#22315)
* [x] https://github.com/nim-lang/Nim/commit/b02c1dd6ca96548b47d978f96278c67bf59e9d9e fixes #22297; return in the finally in the closure iterators (#22300)
* [ ] ~~https://github.com/nim-lang/Nim/commit/5ed44e1ec463b68180e17cfe59c8c68d8c55d406 fixes #22254; fixes #22253; stricteffects bugs on recursive calls (#22294)~~
* [x] https://github.com/nim-lang/Nim/commit/14a9929464b9f658155ed429397216736fccc259 Fix #22281 (#22289)
* [x] https://github.com/nim-lang/Nim/commit/3b377937dec9dd6e7a68e9c95c4ec47d6d21d689 gendepends now supports pkgs2 (#22277)
* [x] https://github.com/nim-lang/Nim/commit/ecc6ab7ee06a5969fd871585de8b93120bd58a2b fixes #22237; fixes #21160; wrong cursor on unowned parameters in the for loop in ORC (#22240)
* [x] https://github.com/nim-lang/Nim/commit/1b132ddaa2734fc43a9c172407fc968cfeec4a24 Fix nimsuggest not showing suggestions for imported tuples (#22241)
* [ ] ~~https://github.com/nim-lang/Nim/commit/a15db5d60b39a24886c692bc9a4e2cb3d5d33ef2 fixes #22175 (#22229)~~
* [x] https://github.com/nim-lang/Nim/commit/86ff37fab8656f7acd08fc9c3fa237f9e022dbf4 fixes #22138 (#22221)
* [x] https://github.com/nim-lang/Nim/commit/2f109595e982bd68b4f4f2fabf934409947b0ee1 reset macrocache after each script evaluation (#22195)
* [ ] ~~https://github.com/nim-lang/Nim/commit/57de460437924a951d393ced8b7c88418fe2541a Don't throw errors on RST tables in Markdown and RstMarkdown modes (#22165)~~
* [x] https://github.com/nim-lang/Nim/commit/ce0909f04729a45f8e56e099fae2471e0504e0ff fixes #22137 (#22170)
* [x] https://github.com/nim-lang/Nim/commit/47635d30315595fc2dbe2162b691aff0f8e0f459 fix Sigaction struct definition (#22160)
* [x] https://github.com/nim-lang/Nim/commit/cb40f11e6c0a8f8df8b429f239483c408c7cc668 uint arithmetic for pointers (#22159)
* [x] https://github.com/nim-lang/Nim/commit/20037a47499ea183afb0e8d2a3f68c2b2952aa5d make `var object` match better than `object` (#22152)
* [ ] ~~https://github.com/nim-lang/Nim/commit/f718f295df3f6ee5d7fd6fc19e39ac663821b00a fix VM uint conversion size bug, stricter int gen on JS (#22150)~~
* [x] https://github.com/nim-lang/Nim/commit/88114948c41f38d7366dc8d80abc09f00c2492fa fixes #21110; duplicate proc definitions for inline iters (#21136)
* [x] https://github.com/nim-lang/Nim/commit/ac7b8b678c9e8eff70bb8147d411664470a882fd fixes #21231; template with module as parameter elides usage/checking of module name specifier (#22109)
* [x] https://github.com/nim-lang/Nim/commit/3ad2e7df1cfb0b454a96dbbc10b2684d1f53dc9b fix #20023 hash for generic tables (#20346)
* [x] https://github.com/nim-lang/Nim/commit/5e529b3bfa7b3ca09cde7237134acd47e47ca48c `strutils.split/rsplit` now return src on an empty sep (#22136)
* [x] https://github.com/nim-lang/Nim/commit/e8d0f1c3aedd8290cc972e3d06f642e88dbe783e fixes #16331; aliasing of tuple construction within a single assignme… (#22113)
* [x] https://github.com/nim-lang/Nim/commit/77beb152141f0efe4d5c93b784e42f973ba46551 fixes #22049; fixes #22054; implicit conversion keeps varness (#22097)
* [x] https://github.com/nim-lang/Nim/commit/3ac2d816010839a6b9a78bf0b2288f32eef7e231 consider object types as declarative in templates (#22106)
* [ ] ~~https://github.com/nim-lang/Nim/commit/b4d9be0f8ae6c97d581e3d32f502a3c323f18475 fixes ilegal recursion (#22105)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/4937aa952b35975fdc76a627ab25116d9b38800b adds another pass for sets fixes #6259 (#22099)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/edb64bcff445d9bfbcf715b697256b230f54c14e fixes explicit deref block (#22093)~~
* [x] https://github.com/nim-lang/Nim/commit/49e11d9dcc00d4c758b754e7a89f9d0253d25ea0 clean up isNilConversion for seqs, strings (#22057)
* [x] https://github.com/nim-lang/Nim/commit/a8d0dda8333f78dfa427e0808ff84280363355d4 allow addressing elements of openArray[char] in VM (#22045)
* [x] https://github.com/nim-lang/Nim/commit/ea91cfb3050bac5c808ed8ab08e12cd33f1dc8ff Improve compiler messages (#22040)
* [x] https://github.com/nim-lang/Nim/commit/ce72b564bce334b2d8a3b3dbea800557bd842e64 retain forced open undeclared ident information (#22019)
* [x] https://github.com/nim-lang/Nim/commit/9f3d1b12907ba8ce36f2708c7439e8e24eb237fe Improve compiler messages (#22028)
* [ ] ~~https://github.com/nim-lang/Nim/commit/2ab948ce53e3d9b80bf9b02644c8ec8991f34d0a post expr blocks colon fix + correct grammar (#21983)~~
* [x] https://github.com/nim-lang/Nim/commit/8e35b3d577cb0a6b216b16668ff5f34a86cfbbab fixes #21974; fixes sameConstant fieldDefect (#21981)
* [ ] ~~https://github.com/nim-lang/Nim/commit/b3e1892eb7f4cb8b2090be7ad12286cc54506e91 fixes #21977; add sideEffects to dirExists, fileExists and symlinkExists (#21978)~~
* [ ] ~~https://github.com/nim-lang/Nim/commit/40f88da90b0589a91f4f60b2ebf49859b79e2247 alternative to #21914; split, rsplit now forbid an empty separator (#21961)~~
* [x] https://github.com/nim-lang/Nim/commit/f47b27d5320ce76757dc67936da9580f94ede293 prevent spamming of thread local forward declarations in C/C++ output (#21955)
* [x] https://github.com/nim-lang/Nim/commit/af3fd5a010b2f30a007c410858effb3095ef2598 fixes #15428 by updating deep open array copy codegen (#21935)
* [ ] ~~https://github.com/nim-lang/Nim/commit/266cc69f1973773228534f074febd153c472b949 fix #21896 asign parameter to global variable generates invalid code (#21900)~~
* [x] https://github.com/nim-lang/Nim/commit/76a98fee650228306a6b1af72e64bb83a9473ef0 fix #21251 Compiler SIGSEGV when using SharedTable  (#21876)
* [x] https://github.com/nim-lang/Nim/commit/28a116a47701462a5f22e0fa496a91daff2c1816 Fixed generic parameters failing to be used in inheritance (#21866)
* [ ] ~~https://github.com/nim-lang/Nim/commit/9c40dd2406e6e83799aa4e3a22e23922318aabd6 fixes #21840; nested local template lookup regression (#21841)~~
* [x] https://github.com/nim-lang/Nim/commit/9810b8cf7ff85a306699d8393ce516501d938e05 just set CallNodes = nnkCallKinds, follows up #21829 (#21833)
* [x] https://github.com/nim-lang/Nim/commit/ebbad9e9604d778c32838c981c8748f3675d2659 cursor fields cannot form reference cycles (#21832)
* [x] https://github.com/nim-lang/Nim/commit/802d57c2374e9048181569ec2fc19501ea790ad3 Add nnkHiddenCallConv to nnkCallKinds (#21781) (#21829)
* [x] https://github.com/nim-lang/Nim/commit/b169dad1e5083eae333ba9a7e11fed74a05385de Improve and refactor cellseqs_v2 in Nim standard library (#21796)
* [x] https://github.com/nim-lang/Nim/commit/71f2e1a502ad231e3356217398e2d7fcd6137967 🚀 Enhancing CellSeq for Better Readability and Maintainability (#21797)
* [ ] ~~https://github.com/nim-lang/Nim/commit/d0c62fa169f3970653ce0d5bbd16e123efb24251 fixes #21753 [backport] (#21802)~~
* [x] https://github.com/nim-lang/Nim/commit/07233ceca0fa220418f1691e70c9e8d49e440737 fixes #21792; enable checks for sum, prod, cumsummed  and cumsum (#21793)
* [ ] ~~https://github.com/nim-lang/Nim/commit/a929e513faf04094d947e462caa653e0dfef20f0 amends #21690 to fix broken Nim to C++ source line mappings (#21784)~~
* [x] https://github.com/nim-lang/Nim/commit/44736d26cdbb0ea5e6010a9ae2bbeadb635d62a1 error on user pragma args (#21776)
* [x] https://github.com/nim-lang/Nim/commit/e5d0907a42112ce28ae2cbd13d095c0d7c23fd91 line info for strformat + fix issue with typed templates (#21761)
* [x] https://github.com/nim-lang/Nim/commit/ca82b4ea16eb7d48b6851110bcb4667570a97f52 underscore as special word (#21766)
* [x] https://github.com/nim-lang/Nim/commit/c2bcfd8cd908265c358c60c4da137783b10a8549 cheap fix for #10853 + better tuple subscript error message (#21767)
* [ ] ~~https://github.com/nim-lang/Nim/commit/91abf35442d6f0861db659c5332b481bd24dfedb improve C/C++ debug output readability (1/N) (#21690)~~
* [x] https://github.com/nim-lang/Nim/commit/560fa9a1fe3c098e00ca6486b425951a3a8cd568 handle quoted routine symbols and non symbols expressions as before (#21740)
* [x] https://github.com/nim-lang/Nim/commit/0f226c0e4865eb27a534fcd8defc34576e222177 fixes #21703; moveOrCopy should consider when vm (#21721)
* [ ] ~~https://github.com/nim-lang/Nim/commit/20b011de19c507380164c46c04cce174842f8e9e refactoring in preparation for better, simpler name mangling that wor… (#21667)~~
* [x] https://github.com/nim-lang/Nim/commit/380dafcc32abed83148f5da78a2aaef608831f8a fix iterator equality + add test for proc equality + fix sameType (#21707)
* [ ] ~~https://github.com/nim-lang/Nim/commit/175a83c2de436b0e84f232fd44d264fb2c79fb14 refact: Remove assertion effect hiding workaround (#21472)~~
* [x] https://github.com/nim-lang/Nim/commit/f9477396a6f21beaa8ffd3de19129b11fe7169f1 static link pthread correctly (#21693)

**Comment by kdeme** [comment]
We also need to find the commit that fixes https://github.com/nim-lang/Nim/issues/22190 and have a backport for that.

**Comment by arnetheduck** [comment]
1.6.16 released
