### ISSUE TITLE
2.0.4/6 backport candidates

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/backport#3]
```
git log --oneline --pretty="format:%m https://github.com/nim-lang/Nim/commit/%H %s" --left-right  --cherry-pick devel...origin/version-2-0
```

* [x] https://github.com/nim-lang/Nim/commit/4c38569229ade43d9570f92e08637f2bcd66bdc5 Change unicode lookup tables to have int32 elements to support platforms where sizeof(int) * [ ] 4 (#23433)
* [x] https://github.com/nim-lang/Nim/commit/50c1e93a7481a79634b5d444806c94c1ea12b8ff fix: use `ErrorColor` for hints marked as errors (#23430)
* [x] https://github.com/nim-lang/Nim/commit/f639cf063f66a160550bcf8955eb3446ca101cc2 fixes #23401; prevents nrvo for cdecl procs (#23409)
* [x] https://github.com/nim-lang/Nim/commit/fb6c8055683051283f6e094b4f3c2eea8c120207 propagate efWantStmt in semWhen (#23400)
* [x] https://github.com/nim-lang/Nim/commit/78c834dd76f273d8813247647531005a1f7db1a6 Fixes an issue where exported types werent being cgen with the `exportc` pragma (#23369)
* [x] https://github.com/nim-lang/Nim/commit/1e20165a15cf8751f74751421a85075a81f799a6 fixes #22166; adds sideeffects for `close` and `setFilePos` (#23380)
* [x] https://github.com/nim-lang/Nim/commit/320311182c904cf4672457b8b02a60303856cb38 fixes #22284; fixes #22282; don't override original parameters of inferred lambdas (#23368)
* [ ] https://github.com/nim-lang/Nim/commit/aa30233ea7f904c466020b8eb1b369e9b49ab79f fixes #23273; forbids methods having importc pragmas (#23324)
* [x] https://github.com/nim-lang/Nim/commit/572b0b67ff15373748dfdde4f470bd45641de990 fixes sink regression for ORC; ref #23354 (#23359)
* [x] https://github.com/nim-lang/Nim/commit/31d755452485eccffa396e0e8432050a63b04c35 fixes #13481; fixes #22708; disable using union objects in VM (#23362)
* [x] https://github.com/nim-lang/Nim/commit/a1e41930f886986fe4153150bf08de9b84d81c6b strformat: detect format string errors at compile-time (#23356)
* [x] https://github.com/nim-lang/Nim/commit/6ce6cd4bb8e59c9f5a2c4588d2d34b9306e03d63 fixes #22723; skips tyUserTypeClasses in injectdestructors (#23341)
* [ ] https://github.com/nim-lang/Nim/commit/d6f0f1aca75b97186baf2d785e30cc426482870d Remove count field from Deque (#23318)
* [x] https://github.com/nim-lang/Nim/commit/dfd778d0562b07653d1853de9f6d85f7c1688146 fixes #23304; uses `snprintf` instead of `sprintf` (#23322)
* [x] https://github.com/nim-lang/Nim/commit/9a4623033547ffa0d6746c91b9817b8353ed8361 assume a module's usage if it contains a passC/passL/compile pragma w… (#23323)
* [x] https://github.com/nim-lang/Nim/commit/35ec9c31bd0bd413f1740feea90f3b97ad5d1b65 fixes refc with non-var destructor; cancel warnings (#23156)
* [ ] https://github.com/nim-lang/Nim/commit/ce68e11641418725a01710bd91b27c7d17c42f64 Remove mask field from Deque (#23299)
* [x] https://github.com/nim-lang/Nim/commit/7d9721007c8c82804450bd32bbf3bbaf806a52f2 fixes regression #22909; don't optimize result init if statements can raise which corrupts the compiler (#23271)
* [x] https://github.com/nim-lang/Nim/commit/e3350cbe6f8549fbc658bd1a99f98abe174d6c2c clean up goto exceptions; remove the setjmp.h dep (#23259)
* [x] https://github.com/nim-lang/Nim/commit/24a606902a4e99ac3d7f58b89db3b023061bc8b0 fixes #23247; don't destroy openarray since it doesn't own the data (#23254)
* [x] https://github.com/nim-lang/Nim/commit/d44b0b186943b3187e6dbc8bc5d304f402d978dc fixes #22597; avoid side effects for call returning openArray types (#23257)
* [ ] https://github.com/nim-lang/Nim/commit/ee984f8836740cb64d88c622ff652e396751edee account for nil return type in tyProc sumGeneric (#23250)
* [ ] https://github.com/nim-lang/Nim/commit/720021908db1f6622c1ebcdad60dff5c2740a80b fixes #23233; Regression when using generic type with Table/OrderedTable (#23235)
* [x] https://github.com/nim-lang/Nim/commit/01097fc1fc70d5c7ce38108d7773e5533fb3743b fix mime types data (#23226)
* [x] https://github.com/nim-lang/Nim/commit/38f9ee0e5850ac9987fe612edcf48cddd1835091 Make std/math classify work without `--passc:-fast-math`. (#23211)
* [x] https://github.com/nim-lang/Nim/commit/b2f79df81cc1fb2cfd4566ffa868043e286eba5c fixes #22218; avoids cursor when copy is disabled (#23209)
* [x] https://github.com/nim-lang/Nim/commit/3fb46fac32b8a1fcf36ac52d09983297251d1213 fixes #12334; keeps `nkHiddenStdConv` for cstring conversions (#23216)
* [ ] https://github.com/nim-lang/Nim/commit/cfd69bad1a1071345cfcd145a7e7f906304f265f fix wrong subtype relation in tuples & infer some conversions (#23228)
* [x] https://github.com/nim-lang/Nim/commit/3ab8b6b2cf4488c114284aa5ad5b7af0d4055312 error on large integer types as array index range (#23229)
* [x] https://github.com/nim-lang/Nim/commit/3379d26629f30e6be8d303a36e220d1039eb4551 fixes #23223; prevents `insert` self-assignment (#23225)
* [x] https://github.com/nim-lang/Nim/commit/f46f26e79aada7195f4d83d8601f0d856520763d don't use previous bindings of `auto` for routine return types (#23207)
* [x] https://github.com/nim-lang/Nim/commit/ab4278d2179639f19967431a7aa1be858046f7a7 fixes #23180; fixes #19805; prohibits invalid tuple unpacking code in for loop (#23185)
* [x] https://github.com/nim-lang/Nim/commit/8484abc2e498bd9738097c06362d442c615a8264 fixes #15924; Tuple destructuring is broken with closure iterators (#23205)
* [ ] ~~https://github.com/nim-lang/Nim/commit/29ac3c9986de5731a32beaf015e81a18dd6bd498 fixes #22923; fixes `=dup` issues (#23182)~~ https://github.com/nim-lang/Nim/issues/23530
* [ ] https://github.com/nim-lang/Nim/commit/62c5b8b2873caac3e56d15738f503e953840e6ca fixes #23129; fixes generated hooks raise unlisted Exception, which never raise (#23195)
* [x] https://github.com/nim-lang/Nim/commit/e8092a54704be254cd7ccb4f5ecfca7cb059fe5c delay resolved procvar check for proc params + acknowledge unresolved statics (#23188)
* [x] https://github.com/nim-lang/Nim/commit/00be8f287a41be42b3763f71beecd959dd6b7aa2 trigger range check with new type inference on nkIntLit [backport:1.6] (#23179)
* [x] https://github.com/nim-lang/Nim/commit/62d8ca43063197272968b4acf8c7a1ef27874c54 don't transform typed bracket exprs to `[]` calls in templates (#23175)
* [x] https://github.com/nim-lang/Nim/commit/a4f3bf374238df96f0982b7106e3702da6b485b1 Fixes #23172 (#23173)
* [x] https://github.com/nim-lang/Nim/commit/3dee1a3e4c81448b67b75068fef06a121f320758 fixes #23139; Cannot get repr of range type of enum (#23164)
* [ ] https://github.com/nim-lang/Nim/commit/74fa8ed59a15caa2ee91f9e559b37728618c3865 Changing generic weight of `tyGenericParam` (#22143)
* [x] https://github.com/nim-lang/Nim/commit/4eaa3b028cd8963799a637c8a4f7f553386fe395 fixes #23167; take `nkOpenSymChoice` into consideration caused by templates [backport] (#23168)
* [x] https://github.com/nim-lang/Nim/commit/c4f98b7696ce74c9952c973b0f09e59234f84917 Recommend hanging indent in NEP1 (#23105)
* [ ] https://github.com/nim-lang/Nim/commit/ccc7c45d718c13714e8e9e1040c29b9b286d2448 `typRel` and `sumGeneric` adjustments (#23137)
* [x] https://github.com/nim-lang/Nim/commit/15c7b76c66cddfbf7465200476d7175e059d3102 Fix cmpRunesIgnoreCase on system where sizeof(int) * [ ] 4. Fixes #23125. (#23138)
* [x] https://github.com/nim-lang/Nim/commit/fc49c6e3ba5081593e4d9af7e04bfb84e97a39f5 fix spurious indent and newlines in rendering of nkRecList (#23121)
* [x] https://github.com/nim-lang/Nim/commit/db9d8003b074cb6d150f7ece467f29006ccefde7 Don't crash for invalid toplevel parseStmt/Expr calls (#23089)
* [x] https://github.com/nim-lang/Nim/commit/941659581add605e8a4ddfc9ff00662aa6234d26 allow replacing captured syms in macro calls in generics (#23091)
* [x] https://github.com/nim-lang/Nim/commit/b3b87f0f8a8091c88461953d686f9772dfb3c4bc Mark `macros.error` as `.noreturn.` (#23081)
* [x] https://github.com/nim-lang/Nim/commit/0bd4d802383518cfbb43fa02375602abdfb6114f Allow `parseAll` to parse statements separated by semicolons (#23088)
* [ ] https://github.com/nim-lang/Nim/commit/94f7e9683fb5c9f643b7e4af367a3a6457d5ad7f Param match relax (#23033)
* [ ] ~~https://github.com/nim-lang/Nim/commit/91efa49550b377e677cb0ff0d10e0c1192955b63 Overloads passed to static proc parameters now convert to the desired… (#23063)~~ https://github.com/nim-lang/Nim/issues/23533
* [x] https://github.com/nim-lang/Nim/commit/1b7b0d69db41b3c5a27cca643d66c0acabbe41df fixes #9381; Fix double evaluation of types in generic objects (#23072)
* [x] https://github.com/nim-lang/Nim/commit/7e1ea50bc3a495bc8feb69ceb9856a0a28ecc2e9 fixes #23060; `editDistance` wrongly compare the length of rune strings (#23062)
* [ ] ~~https://github.com/nim-lang/Nim/commit/8cc3c774c8925c3d21626d09b41ad352bd898e4a Look up generic parameters when found inside semOverloadedCall, fixin… (#23054)~~ https://github.com/nim-lang/Nim/issues/23533
* [x] https://github.com/nim-lang/Nim/commit/d20b4d5168780b9c6a3bd2fde28b171cb7414c98 fixes #23019; Regression from 2.0 to devel with raise an unlisted exc… (#23034)
* [ ] https://github.com/nim-lang/Nim/commit/0d24f765461785e5648ee580e0a4158eb344ee97 fixes #22552 (#23014)
* [x] https://github.com/nim-lang/Nim/commit/7ea5aaaebb10369f202490581da6912b491503dd fixes #23001; give a better warning for PtrToCstringConv (#23005)
* [x] https://github.com/nim-lang/Nim/commit/9140f8e2212c91347704cec0f98c0345ddf0ea1e Fix endsInNoReturn for case statements (#23009)
* [x] https://github.com/nim-lang/Nim/commit/96513b2506d9057744da9926986181294a3da653 fixes #22926; Different type inferred when setting a default value for an array field (#22999)
* [x] https://github.com/nim-lang/Nim/commit/795aad4f2a0032ed9b54a7b89dc08b420981e208 fixes #22996; `typeAllowedCheck` for default fields (#22998)
* [x] https://github.com/nim-lang/Nim/commit/5b2fcabff5dc28b3df49960c052feeda98dbb7d0 fix: std/marshal unmarshaling of ref objects (#22983)
* [x] https://github.com/nim-lang/Nim/commit/cecaf9c56b1240a44a4de837e03694a0c55ec379 fixes #22939; fixes #16890; push should but doesn't apply to importc … (#22944)
* [ ] ~~https://github.com/nim-lang/Nim/commit/5dafcf4957a225b1f015d131299e51735e7bb1d3 fixes #22913; fixes #12985 differently push-ing pragma exportc genera… (#22941)~~ https://github.com/nim-lang/Nim/issues/23519
* [x] https://github.com/nim-lang/Nim/commit/0f7488e20f399b7866167f782e98426db215f918 let `InotifyEvent` type `sizeof`-able (#22958)
* [x] https://github.com/nim-lang/Nim/commit/39fbd30513fbabb8ff189dcb60991a08f912f6da Fix OSError `errorCode` field is not assigned a value (#22954)
* [x] https://github.com/nim-lang/Nim/commit/0dc3513613f87beb6ab5a590360ced7c9d33b1e3 fixes #22932; treats closure iterators as pointers (#22934)
* [x] https://github.com/nim-lang/Nim/commit/2e070dfc76a1badfaad08d62b0f3f02f6ba2bc02 fixes #22673; Cannot prove that result is initialized for a placehold… (#22915)
* [x] https://github.com/nim-lang/Nim/commit/58c44312afba755f73ba2ec7ab73daea7768e41d reserve `sysFatal` for `Defect` (#22158)
* [x] https://github.com/nim-lang/Nim/commit/af556841ac57655f5b2ffe34de401a981b6eaf94 fixes #22860; suppress `AnyEnumConv` warning when iterating over set (#22904)
* [x] https://github.com/nim-lang/Nim/commit/95e5ad6927af309552857686bf2c74bfac36cbb7 fixes #22902; borrow from proc return type mismatch (#22908)
* [x] https://github.com/nim-lang/Nim/commit/92141e82ede93028be5781d6f4e906cefa3b03eb fixes #22883; replace `default(typeof(` with `reset`; suppress `Unsaf… (#22895)
* [x] https://github.com/nim-lang/Nim/commit/c13c48500b527cb483480702390b1f230ac896a4 Fix #22826: Don't skip generic instances in type comparison (#22828)
* [x] https://github.com/nim-lang/Nim/commit/e10878085eaf215a6782cde5c2ea79d4cdf0f40e fixes #22844; uses arrays to store holeyenums for iterations; much more efficient than sets and reasonable for holeyenums (#22845)
* [x] https://github.com/nim-lang/Nim/commit/f5d70e7fa7195658e3200f71a1653e07fe81275a fixes #19250; fixes #22259; ORC AssertionDefect not containsManagedMemory(n.typ) (#22823)
* [x] https://github.com/nim-lang/Nim/commit/ecaccafa6c18e0b92cd5f75d3363d61c0866dec9 fixes #22790; use cast suppress AnyEnumConv warnings for enums withou… (#22813)
* [x] https://github.com/nim-lang/Nim/commit/9d7acd001f268e2b9dab9228ca5e22bf75028704 use lent for the return value of index accesses of tables (#22812)
* [x] https://github.com/nim-lang/Nim/commit/14d25eedfd5ada29fcd3690919e40623563b98fa suppress incorrect var T destructor warnings for newFinalizer in stdlib (#22810)
* [x] https://github.com/nim-lang/Nim/commit/2cf214d6d46d11024e6420520e39eed779da284e allows cast int to bool/enum in VM (#22809)
* [x] https://github.com/nim-lang/Nim/commit/81b2ae747e307f4ab171d3b62a0e6ea8b6a81d3d fixes #8893; guard against array access in renderer (#22807)
* [x] https://github.com/nim-lang/Nim/commit/efa64aa49b11e93461626e84b9f67b6185f26e1f fixes #22787; marks `var section` in the loop as reassign preventing cursor (#22800)
* [x] https://github.com/nim-lang/Nim/commit/1a6ca0c6047ac1f1489f2b45e4966ddca1f40e46 arraymancer switches to the offical URL (#22782)
* [x] https://github.com/nim-lang/Nim/commit/b2ca6bedae6420396682cbf06b3c628cfcf9baf1 Make `typeRel` behave to spec (#22261)
* [x] https://github.com/nim-lang/Nim/commit/5eeafbf55029816e5022d9d6aa9ed3b0acf2d3ba fixes #22696; func `strutils.join` for non-strings uses proc `$` which can have side effects  (#22770)
* [x] https://github.com/nim-lang/Nim/commit/0c179db6579ee5ae853603bf8d8efe23785cb7ab case macro now can be used inside generic. Fixes #20435 (#22752)
* [x] https://github.com/nim-lang/Nim/commit/285cbcb6aa36147e9b9c024ceed78e46526dd1ea ref #19727; implement `setLenUninit` for seqsv2 (#22767)
* [x] https://github.com/nim-lang/Nim/commit/a7a0cfe8eb5942d799b4b7e2fdf26bcb9ff8ffab fixes #10542; suppresses varargs conversion warnings (#22757)
* [x] https://github.com/nim-lang/Nim/commit/3979e83fcbf5e7bda9a1bad55fa9d594f36158de fixes #22706; turn "unknown hint" into a hint (#22755)
* [x] https://github.com/nim-lang/Nim/commit/a1b6fa9420db09f2660ad5919d2b96673f324f8f fixes #22246; generate __builtin_unreachable hints for case defaults (#22737)
* [x] https://github.com/nim-lang/Nim/commit/d82bc0a29fea53a172260a3b3301b90a96974274 items, pairs and friends now use `unCheckedInc` (#22729)
* [x] https://github.com/nim-lang/Nim/commit/fefde3a735c3bc931a4d3289e43f3b95f65e1256 fixes compiler crash by preventing exportc on generics (#22731)
* [x] https://github.com/nim-lang/Nim/commit/51cb493b221e704efce126049f9f320eb1cb1a36 make parseEnum skip type aliases for enum type sym (#22727)
* [x] https://github.com/nim-lang/Nim/commit/741285b335343ad61afc2d48778c52cd097d1249 Update osfiles.nim, make `moveFile` consider permission on *nix (#22719)
* [x] https://github.com/nim-lang/Nim/commit/63c2ea5566cc7a0983cc748a3d4855d24beeebda fixes incorrect cint overflow in system (#22718)
* [ ] https://github.com/nim-lang/Nim/commit/deefbc420e218459ffc6ccf915f625cd48e083b4 fixes `result` requires explicit initialization on noReturn code (#22717)
* [x] https://github.com/nim-lang/Nim/commit/fcf4c1ae172080b8ef00b173977c223836bdebf2 Fix #22713: Make size unknown for tyForward (#22714)
* [x] https://github.com/nim-lang/Nim/commit/8836207a4e68c177d5059131df05a9d433dd3c8d implement semgnrc for tuple and object type nodes (#22709)
* [x] https://github.com/nim-lang/Nim/commit/38b58239e882eaa905bafa49237f0b9ca9d43569 followup of #22568 (#22690)
* [x] https://github.com/nim-lang/Nim/commit/ac1804aba665b34a01cb014183f8fff0ba6db738 refactor semtempl ident declarations, some special word use (#22693)
* [x] https://github.com/nim-lang/Nim/commit/b1a8d6976ff41a1cde84647b7dbade9316fbcecf fixes the `discVal` register is used after free in vmgen (#22688)
* [x] https://github.com/nim-lang/Nim/commit/fbb5ac512cd03a67a3364469132a881341e10e1c Remove some unnecessary initialization in `seq` operations (#22677)
* [x] https://github.com/nim-lang/Nim/commit/2ce9197d3ad705b3abb5f40f0c27543d7bf03381 [minor] merge similar branches in vmgen (#22683)
* [x] https://github.com/nim-lang/Nim/commit/8853fb07753756dbe29364e8a32081462367215d Make `newSeqOfCap` not initialize memory. (#21842)
* [x] https://github.com/nim-lang/Nim/commit/5f13e15e0a6f90c462a71cd30addc677f688c4dc fixes #22664; guard against potential seqs self assignments (#22671)
* [x] https://github.com/nim-lang/Nim/commit/d45270bdf721e195a9dae344f9a3285d066c3932 fixes  #22662 Procs with constructor pragma doesn't initialize object's fields (#22665)
* [x] https://github.com/nim-lang/Nim/commit/2a8c759df0e8a952f7cbea8539e3fb7aa234795a Fix #21742: Check generic alias depth before skip (#22443)
* [x] https://github.com/nim-lang/Nim/commit/ed9e3cba07c9d03714b4ea22e50dcc7e706e0bed make getType nodes of generic insts have full inst type (#22655)
* [x] https://github.com/nim-lang/Nim/commit/480e98c479035a8a19ff543bace3616d202e1ea2 resolve unambiguous enum symchoices from local scope, error on rest (#22606)
* [x] https://github.com/nim-lang/Nim/commit/bd6adbcc9d5a22f686eed7bc988a1c0b1b0a17e4 fix isNil folding for compile time closures (#22574)
* [x] https://github.com/nim-lang/Nim/commit/9f1fe8a2da27abc1e93a05debbb2622b524aae0d Fix the problem where instances of generic objects with `sendable` pragmas are not being cached (#22622)
* [x] https://github.com/nim-lang/Nim/commit/0c6e13806d0abfad30b8a4bd9f1fe7858ff2125a fixes internal error: no generic body fixes #1500 (#22580)
* [x] https://github.com/nim-lang/Nim/commit/f1789cc465bcabc7afe0fe991df615246cfadb3b resolve local symbols in generic type call RHS (#22610)
* [x] https://github.com/nim-lang/Nim/commit/53d9fb259fc7d36660be20be0a199625ef126376 don't update const symbol on const section re-sems (#22609)
* [x] https://github.com/nim-lang/Nim/commit/affd3f78587f1b18a8b4bc2fc51967cd55cb7531 fixes #22613; Default value does not work with object's discriminator (#22614)
* [x] https://github.com/nim-lang/Nim/commit/ba158d73dc23fb6e61ebe88f6485f95c8dcb96c2 type annotations for variable tuple unpacking, better error messages (#22611)
* [x] https://github.com/nim-lang/Nim/commit/6b955ac4af834fb9765b5b2a2588a5feb1de31f0 properly fold constants for dynlib pragma (#22575)
* [x] https://github.com/nim-lang/Nim/commit/0b78b7f595ef96a9769e0d59167239c611b9857a fix #22548;environment misses for type reference in iterator access n… (#22559)
* [x] https://github.com/nim-lang/Nim/commit/101337885459decedc9dc3301b1ff04cf8c54c32 fixes a strictdef ten years long vintage bug, which counts the same thing twice (#22549)
* [x] https://github.com/nim-lang/Nim/commit/bc9785c08d53c2f94f62738e541508592c9b3b24 Fix `getAppFilename` exception handling (#22544)
* [x] https://github.com/nim-lang/Nim/commit/53d43e96716539d96e6a1e5f3926a3fe3a11e2dd round out tuple unpacking assignment, support underscores (#22537)
* [x] https://github.com/nim-lang/Nim/commit/602f537eb2445b442b6cddecf9f55bf476068ea9 allow non-pragma special words as user pragmas (#22526)
* [x] https://github.com/nim-lang/Nim/commit/c0ecdb01a967b1b903a756abf7202bfbd95ec7b1 Fix #21722 (#22512)
* [x] https://github.com/nim-lang/Nim/commit/98c39e8e571b95e7d9351c7115f897ce9af1a218 cascade tyFromExpr in type conversions in generic bodies (#22499)
* [x] https://github.com/nim-lang/Nim/commit/09d0fda7fde69087c75a102b219d5eebf1b86db2 fixes #22469; generates nimTestErrorFlag for top level statements (#22472)
* [x] https://github.com/nim-lang/Nim/commit/48da472dd2e625d2d794907afd33a4a153fa2dc1 fix #22448 Remove `structuredErrorHook` temporary in `tryConstExpr` (#22450)
* [x] https://github.com/nim-lang/Nim/commit/faf1c91e6a418e21d56ac6e45e1dbc851f9ffd22 fixes move sideeffects issues [backport] (#22439)
* [x] https://github.com/nim-lang/Nim/commit/05f7c4f79db096581352cbe20666f82300d21580 fixes a typo (#22437)
* [x] https://github.com/nim-lang/Nim/commit/2aab03bdfb0a216820541de7dcb34950a017bf18 fix #19304 Borrowing std/times.format causes Error: illformed AST (#20659)
* [x] https://github.com/nim-lang/Nim/commit/baf350493b08d5e1ee25f61b7d7eff33c3499487 Fix #21760 (#22422)
* [x] https://github.com/nim-lang/Nim/commit/d53a89e4539a33d9f7cf8416155d7cb700628872 fix #12938 index type of array in type section without static (#20529)
* [x] https://github.com/nim-lang/Nim/commit/989da75b84e15a6d585e8b03d2bcd0c42a90c2fb fix #20891 Illegal capture error of env its self (#22414)
* [x] https://github.com/nim-lang/Nim/commit/10a6e4c236b8d4d609a07b29ad5b7b4e517cd367 clean up `gc:arc` or `gc:orc` in docs and in error messages (#22408)
* [x] https://github.com/nim-lang/Nim/commit/37d8f32ae9ead55a065ae42636e88265ea17ce4a fix #18823 Passing Natural to bitops.BitsRange[T] parameter in generi… (#20683)
* [x] https://github.com/nim-lang/Nim/commit/614a18cd05bda525f62310578115ecc6c41b7e09 Delete parse directory, which was pushed wrongly before [backport] (#22401)
* [x] https://github.com/nim-lang/Nim/commit/137d608d7d68a91c99149aa1127dd675ee45f751 add test for #3907 (#21069)
* [x] https://github.com/nim-lang/Nim/commit/e0396900ed74eb821641d026a68415199fc4a257 Prevent early destruction of gFuns, fixes AddressSanitizer: heap-use-after-free (#22386)
* [x] https://github.com/nim-lang/Nim/commit/9872453365f0782277aa93045e4c2461d1b7585a destructors: better docs [backport:2.0] (#22391)
* [x] https://github.com/nim-lang/Nim/commit/db435a4a797adbbd4dd42edf89267902c0b2e34f Fix searchExtPos so that it returns -1 when the path is not a file ext (#22245)
* [x] https://github.com/nim-lang/Nim/commit/26f183043f9e58eb4954d50a5d130d8684909936 fix #20883 Unspecified generic on default value segfaults the compiler (#21172)
* [x] https://github.com/nim-lang/Nim/commit/7c2a2c8dc810a837b93ee0e8bcaf6d8969f5a54a fixes a typo in the manual (#22383)
* [x] https://github.com/nim-lang/Nim/commit/fb7acd66001a5f1bc018e1e1e9b1ebc792462e50 follow up #22322; fixes changelog (#22381)
* [x] https://github.com/nim-lang/Nim/commit/d37b620757c0a4987ee349f246df30def8613b9b Make `repr(HSlice)` always available (#22332)
* [x] https://github.com/nim-lang/Nim/commit/825a0e7df40100d92e87fc421a135a84b94f818f fixes #22362; Compiler crashes with staticBoundsCheck on (#22363)
* [x] https://github.com/nim-lang/Nim/commit/f3a7622514f24740c6b33f0c37ebe6339ad5b70d fixes #22360; compare with the half of randMax (#22361)

**Comment by narimiran** [comment]
@ringabout Even with new backports, the nightlies are still failing with:
`os.nim(678, 30) Error: getApplOpenBsd() can raise an unlisted exception: ref OSError`

Since this happens only on the nightlies, and not with the regular Nim CIs or to me locally, it is hard for me to reproduce.

Last successful nightlies build was before I started doing backports from this list, so I'm guessing the problematic commit is somewhere in the bottom 1/3 of this list (the oldest commit is at the bottom). Based on the commit messages in the list, can you maybe tell what might be causing it or, alternatively, how to fix the error?

**Comment by narimiran** [comment]
Found it!!
I need to backport https://github.com/nim-lang/Nim/pull/22585, which deals with exactly this error.

**Comment by narimiran** [comment]
@arnetheduck The work on this list of commits has been completed. The "missing backports" (onec without a checkmark on the list) are commits which cause problems on the `version-2-0` branch (each has been backported and then tested).

As it is more than a month since you made this list, if you want — make another list with recent `devel` commits which you would like to see in Nim 2.0.x, and I can work on backporting them.

**Comment by arnetheduck** [comment]
@narimiran great, thanks! I'll take a look in a bit

@metagn https://github.com/nim-lang/Nim/commit/941659581add605e8a4ddfc9ff00662aa6234d26 - what would it take to backport this one?

**Comment by metagn** [comment]
> @metagn nim-lang/Nim@9416595 - what would it take to backport this one?

Should be no trouble afaik, a direct cherrypick could work

**Comment by narimiran** [comment]
> Should be no trouble afaik, a direct cherrypick could work

Ok, let me try to backport it again. Maybe this time (with more commits backported) it'll work.

**Comment by narimiran** [comment]
> Should be no trouble afaik, a direct cherrypick could work

When I cherry pick your commit, `tests/concepts/tmatrixconcept.nim` fails with `Error: unhandled exception: index 1 not in 0 .. 0 [IndexDefect]`.
That test file is the same in `devel`, so it's probably some other commit(s) that need to be backported for this to work.

**Comment by metagn** [comment]
Then I would say  https://github.com/nim-lang/Nim/commit/e8092a54704be254cd7ccb4f5ecfca7cb059fe5c might fix it, but there may have been a backport attempt on this already?

**Comment by narimiran** [comment]
> Then I would say https://github.com/nim-lang/Nim/commit/e8092a54704be254cd7ccb4f5ecfca7cb059fe5c might fix it, but there may have been a backport attempt on this already?

I've tried it again now, on top of the previously mentioned commit, and it still doesn't fix the error in `tmatrixconcept.nim`.

Next idea? :)

**Comment by metagn** [comment]
None off the top of my head, I'll try to figure out what's failing from the stacktrace when I get the chance

**Comment by metagn** [comment]
The issue is with sempass2 not being able to handle the weirdness of the type of the `type` keyword, changing:

https://github.com/nim-lang/Nim/blob/fcb8461efab2ef7bdd976f82af8c7d1390f502ac/compiler/sempass2.nim#L891

to:

```nim
    if a.kind != nkSym or a.sym.magic notin {mNBindSym, mFinished, mExpandToAst, mQuoteAst, mType}:
```

(i.e. adding `mType` to the excluded sym magics) fixes it. My guess is the "type refactor" PRs dealt with this some other way but they are pretty big. We could push this change to just 2.0 or we can add it to devel then backport it for symmetry as it should be harmless.

I forgot to mention https://github.com/nim-lang/Nim/commit/941659581add605e8a4ddfc9ff00662aa6234d26 also has a followup https://github.com/nim-lang/Nim/commit/4b1a84170786653f60313f7bdf56efa3928c2a3a and probably needs another one down the line to address https://github.com/nim-lang/Nim/issues/23386.

**Comment by narimiran** [comment]
> I forgot to mention https://github.com/nim-lang/Nim/commit/941659581add605e8a4ddfc9ff00662aa6234d26 also has a followup https://github.com/nim-lang/Nim/commit/4b1a84170786653f60313f7bdf56efa3928c2a3a

Now I backported that followup + added `mType` to the line you mention. 

`tests/concepts/tmatrixconcept.nim` now passes on my machine, but let's see if CIs find any other problem.

**Comment by narimiran** [comment]
> let's see if CIs find any other problem.

No problem found. All mentioned commits are now available in `version-2-0` branch.

**Comment by narimiran** [comment]
With @metagn's fix (https://github.com/nim-lang/Nim/pull/23571) backported, I consider this list of commits done.

@arnetheduck, please open a new issue with the recent commits you would like to see backported.
