### ISSUE TITLE
2.0.6 backport candidates

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/backport#4]
```
git log --oneline --pretty="format:%m https://github.com/nim-lang/Nim/commit/%H %s" --left-right  --cherry-pick devel...origin/version-2-0
```

* [x] https://github.com/nim-lang/Nim/commit/b838d3ece1e8530f355b5078b2daa96ac01acab5 doc(format): ospaths2,strutils: followup #23560 (#23629)
* [x] https://github.com/nim-lang/Nim/commit/b3b26b2e56df580b1a4190fb28ef4e05f0cff514 doc(format): system.nim: doc of hostCPU for `loongarch64` (#23621)
* [ ] https://github.com/nim-lang/Nim/commit/b87732b5f13a39b00a82713a465db6c2f0fef40a fixes #16671; openarray conversion for object construction (#23618)
* [x] https://github.com/nim-lang/Nim/commit/0ba932132e56d30de7af268f3268b3141ad22bc8 Support NetBSD/aarch64 (#23616)
* [x] https://github.com/nim-lang/Nim/commit/2c8551556e5b51b7a7e487b1043b92d4ad34dbf0 fixes lifting subtype calling parent's hooks (#23612)
* [x] https://github.com/nim-lang/Nim/commit/c08356865da1386a4c999e7d2df23f13979a5c05 closes #15778; adds a test case (#23613)
* [ ] https://github.com/nim-lang/Nim/commit/81a937ce1f23e443a2b60375a0961bafa5b8bd06 ignore modules when looking up symbol with expected type (#23597)
* [ ] ~~https://github.com/nim-lang/Nim/commit/c101490a0c3422cde5a6d2fd686e5ff5feb7237f remove bad type inference behavior for enum identifiers (#23588)~~ --> https://github.com/nim-lang/Nim/pull/23593
* [x] https://github.com/nim-lang/Nim/commit/1eb9aac2f7a8469a682528a0d63128d599fabae7 adds Nim-related mimetypes back (#23589)
* [x] https://github.com/nim-lang/Nim/commit/2e3777d6f39fd3593a69a498a5524db2006fdc91 Improve strutils.rsplit doc, proc and iterator have oppose result order. (#23570)
* [x] https://github.com/nim-lang/Nim/commit/2995a0318be391097f17cb764556294dca5695e8 fixes #23552; Invalid codegen when trying to mannualy delete distinct seq (#23558)
* [x] https://github.com/nim-lang/Nim/commit/63398b11f51529d8a3350853fcf7b7a1cf522b7a Add a note about the sideeffect pragma (#23543)
* [x] https://github.com/nim-lang/Nim/commit/d8e1504ed1fd2371f2ab7784c0f4b5f6376325a5 Add Complex version of almostEqual function (#23549)
* [x] https://github.com/nim-lang/Nim/commit/1ad4e80060f22275b2f443bd8630e2573619e487 fixes #22409; don't check style for enumFieldSymChoice in the function (#23580)
* [x] https://github.com/nim-lang/Nim/commit/6cc783f7f363a4cecd390563ca4fa1780c9af9d1 fixes #23442, fix for FileId under Windows (#23444)
* [x] https://github.com/nim-lang/Nim/commit/36bf3fa47b81e1670bb82df5cc7e22334a9dbc32 fixes #23556; typeinfo.extendSeq generates random values in ORC (#23557)
* [x] https://github.com/nim-lang/Nim/commit/d772186b2dbacdbeceaf2cd3ed3bd583f912e6e3 Update unicode.nim: cmpRunesIgnoreCase: fix doc format (#23560)
* [x] https://github.com/nim-lang/Nim/commit/185e06c92362083c06c76f87e325889b1c9dc659 fixes #23419; internal error with void in generic array instantiation (#23550)
* [x] https://github.com/nim-lang/Nim/commit/d09c3c0f58eb9f1f4cf07fa98a9686aa19778f16 fixes #23321; Error: internal error: openArrayLoc: ref array[0..0, int] (#23548)
* [x] https://github.com/nim-lang/Nim/commit/47594eb9091e788e672c1020f18d84a54bdcbf37 fix typo: "As can been seen" to "As can be seen" (#23544)
* [x] https://github.com/nim-lang/Nim/commit/f682dabf71f35833e934a79007906f94d8d32c92 fixes #23531; fixes invalid meta type accepted in the object fields (#23532)
* [x] https://github.com/nim-lang/Nim/commit/0b0f185bd1db2500079aefd888078b6bd1094270 fixes #23536; Stack trace with wrong line number when the proc called inside for loop (#23540)
* [x] https://github.com/nim-lang/Nim/commit/407c0cb64a804e6f5ffa693ec0e79c9171393a29 fixes #23522; fixes pre-existing wrong type for iter in `liftIterSym` (#23538)
* [x] https://github.com/nim-lang/Nim/commit/4601bb0255335e2c1dfc78ebc33312933215ee95 fixes #23525; an 'emit' pragma cannot be pushed (#23537)
* [x] https://github.com/nim-lang/Nim/commit/cd3cf3a20e7bf6a115cd836ccc0c55ab07bcf3e9 fixes #23524; global variables cannot be analysed when injecting `move` (#23529)
* [x] https://github.com/nim-lang/Nim/commit/7e3bac92357b6fc3f959bdf81b2ad58c2111f8ab * fix for the debug line info code generation (#23488)
* [x] https://github.com/nim-lang/Nim/commit/60af04635f44e655c7928da36fc9394e11367d18 fix #23518 - `* [ ]expr> is` crashes nimsuggest (#23523)
* [x] https://github.com/nim-lang/Nim/commit/acd4c8a3530c42143541b7d891aa61fd0af3f8d3 fixes #23505; fixes injectdestructors errors on transformed addr (deref) refs (#23507)
* [x] https://github.com/nim-lang/Nim/commit/20698b8057b09ace67ff0bc932aa552157ee7c9d fixes #23494; Wrong type in object construction error message (#23504)
* [x] https://github.com/nim-lang/Nim/commit/1bd095521856d4d1f9fb1b6ba580df3c815196f6 fix JSON deep copy description (#23495)
* [x] https://github.com/nim-lang/Nim/commit/73b0b0d31c156392c64b8b088402695c7e27f0f0 stop gensym identifiers hijacking routine decl names in templates (#23392)
* [x] https://github.com/nim-lang/Nim/commit/c23d6a3cb92a7f4d4a96691148359b917c55d2af Update encodings.nim, fix `open` with bad arg raising no `EncodingError` (#23481)
* [x] https://github.com/nim-lang/Nim/commit/f175c81079bdab39a70d6a29311e0dfba34f612c fixes #23440; fixes destruction for temporary object subclass (#23452)
* [x] https://github.com/nim-lang/Nim/commit/dee55f587f4e3cfc8ffe28e4a41eba9c8ed7f2f8 Update syncio.nim, fixes "open by FileHandle" doesn't work on Windows (#23456)
* [x] https://github.com/nim-lang/Nim/commit/4b6a9e4add2af2a458d171b23030acb5d1c70ecb fixes #23422; card regression (#23437)
* [x] https://github.com/nim-lang/Nim/commit/a24990bd8cca735fa1805279a7cd3f42e22240cd fixes #23429; rework `--verbosity` with warnings/hints (#23441)
* [x] https://github.com/nim-lang/Nim/commit/afc30a3b936f35bdbfdc59b4e3d44f25a1273525 Fix compile time errors when using tables on 8/16-bits systems. (#23450)
* [x] https://github.com/nim-lang/Nim/commit/cbf48a253f134dea5cc8d8b2393b7bf6310cc8fe Update manual.md (#23393)
* [x] https://github.com/nim-lang/Nim/commit/b387bc49b5425a7b555972184f5f6078b14d4a8b chore: fix some typos (#23412)
* [ ] https://github.com/nim-lang/Nim/commit/899ba01ccf3edd9928d2c60314b7d75c5730310c + added nimsuggest support for exception inlay hints (#23202)
* [x] https://github.com/nim-lang/Nim/commit/6ebad30e7a96c67cc7a55aa3248849313c9f4e52 closes #22846; adds a test case (#23374)
* [x] https://github.com/nim-lang/Nim/commit/a2584c779b0debb54cdd0111f9ad845fbfe33e97 closes #15751; adds a test case (#23372)
* [x] https://github.com/nim-lang/Nim/commit/d373d304ff6b17dc8ae39760bb8a45e5537d807e closes #10219; adds a test case (#23370)
* [x] https://github.com/nim-lang/Nim/commit/2081da3207b004e21537cf079c8e7f583bc66d76 makes nimsuggest listen on localhost by default (#23351)
* [x] https://github.com/nim-lang/Nim/commit/a61943490479daf9716f310e94130b016a99abe0 remove obselete doc with nimrtl (#23358)
* [x] https://github.com/nim-lang/Nim/commit/90fe1b340f93622f5f101ee93306b386a30eb206 Dont mangle when targeting cpp (#23335)
* [x] https://github.com/nim-lang/Nim/commit/15577043e89f4a1b80f4d8fd4fab4e9fe7e08f33 Fix nimsuggest highlight for import statements (#23263)
