### ISSUE TITLE
2.0.14 backport candidates

### ISSUE THREAD

**Issue by tersec** [nim-lang/backport#7]
- [x] https://github.com/nim-lang/Nim/commit/f485973459a6cfce80497251512df13894e8fda6 Fix exitnow signature, mark as .noreturn (#24533)
- [x] https://github.com/nim-lang/Nim/commit/e7f48cdd5c17cbd0c1c74c2c1f360ae2ea122b64 fixes #24472; let symbol created by template is reused in nimvm branch (#24473)
- [x] https://github.com/nim-lang/Nim/commit/96043bdbb7c777841b98aa7786eba0d6dba814da fix crash with tyBuiltInTypeClass matching itself (#24462)
- [ ] https://github.com/nim-lang/Nim/commit/45e21ce8f1f06c8b85f574cb830b429f3997a2e4 fix jsonutils macro with generic case object (#24429)
- [x] https://github.com/nim-lang/Nim/commit/3e47725c08b42515d17d77b3a6c9cc3029e5681c gensym anonymous proc symbols (#24422)
- [x] https://github.com/nim-lang/Nim/commit/74df699ff1ab913d9ca58a198125f5ad561d289f fixes #24371; incorrect importc wrapper incompatible with gcc 14 on Windows (#24388)
- [x] https://github.com/nim-lang/Nim/commit/815bbf0e7312b62de6a8df96349329dbb1740fb9 fixes #23545; C compiler error when default initializing an object field function (#24375)
- [x] https://github.com/nim-lang/Nim/commit/aa90d00caf1277decb33575397e64d544d0b6eb4 fixes #18081; fixes #18079; fixes #18080;  nested ref/deref'd types (#24335)
- [x] https://github.com/nim-lang/Nim/commit/67442471ae4504bc074c8bb02308613fadc199f8 Fix broken poll and nfds_t bindings (#24331)
- [x] https://github.com/nim-lang/Nim/commit/0347536ff2649e889cb11606a80293bf61043604 fixes #24319; `move` doesn't work well with (deref (var array)) (#24321)
- [x] https://github.com/nim-lang/Nim/commit/6df050d6d2e6e0b62aff3bba093149e15c6e1060 only generate first field for default value of union (#24303)
- [x] https://github.com/nim-lang/Nim/commit/b0e6d28782ce8c3d8e0b4a64e01f21d6f900648f fix logic for `dcEqIgnoreDistinct` in `sameType` (#24197)
- [ ] https://github.com/nim-lang/Nim/commit/7cbe031909e90ae7896aee49382455f428a5c52a fix trivial segfault in sigmatch for static types (#24196)
- [x] https://github.com/nim-lang/Nim/commit/1fbb67ffe9d3ec71fb1424609831eaca648c96d3 make distinct conversions addressable in VM (#24124)
- [ ] https://github.com/nim-lang/Nim/commit/b5f2eafed1438e612b7f269e95422a52893f7a5d don't match arguments with typeclass type in generics (#24123)
- [x] https://github.com/nim-lang/Nim/commit/24e5b21c900811ae8d0a69e06fc35fdd884b3ddc fix regression with generic params in static type (#24075)
- [x] https://github.com/nim-lang/Nim/commit/7de4ace94908f515a98fbe6f3a4a022b6fa9e3f8 fix int32's that should be uint32 on BSD & OSX (#24078)
- [x] https://github.com/nim-lang/Nim/commit/cd22560af5f13a7c024b97e2f3de2b1fe2439eb3 fix string literal assignment with different lengths on ARC (#24083)
- [x] https://github.com/nim-lang/Nim/commit/bf865fa75aba5ed61f123e528044285a87bdd0b1 fix undeclared identifier in templates in generics (#24069)
- [x] https://github.com/nim-lang/Nim/commit/11ead19bc1c811f8733637d8be44833803d0a0af fixes #24034; fixes lent types after taking implicit address (#24035)
- [x] https://github.com/nim-lang/Nim/commit/04da0a6028a4a0d469a10567a35655646f4957c2 fix subscript magic giving unresolved generic param type (#23988)
- [x] https://github.com/nim-lang/Nim/commit/1befb8d4a3559b4611921e851a1fcc64c1b9a17d include generic bodies in allowMetaTypes (#23968)
- [x] https://github.com/nim-lang/Nim/commit/31ee75f10e6482cd482d329507190ac850eee2cf bypass constraints for tyFromExpr in generic bodies (#23863)
- [x] https://github.com/nim-lang/Nim/commit/f765898a7518f5c6bbebffd4217ccc35fd02747d Set type of object constructor during annotateType (#23852)
- [ ] https://github.com/nim-lang/Nim/commit/8096fa45bdf5367f0d89ffe22ba5776ad1abf097 fixes #23725; Size computations work better when they are correct (#23758)
- [x] https://github.com/nim-lang/Nim/commit/2c83f94544b9acc6d06fd6b7fcf035e5cb0aa8eb Check for nil in cstringArrayToSeq (#23747)
- [x] https://github.com/nim-lang/Nim/commit/e6f66e4d131fb8cf3236df6cb14e219dbb5d0c77 fixes 12381, HttpClient socket handle leak (#23575)
- [x] https://github.com/nim-lang/Nim/commit/39f2df19723d98eaa006cfd0ef13ec93d9f8c1c5 fixes #23295; don't expand constants for complex structures (#23297)
- [x] https://github.com/nim-lang/Nim/commit/1e9a3c438bed693bc95d5b1a9501e1386163e1cc fixes #18104; tranform one liner var decl before templates expansion (#23294)
- [x] https://github.com/nim-lang/Nim/commit/720021908db1f6622c1ebcdad60dff5c2740a80b fixes #23233; Regression when using generic type with Table/OrderedTable (#23235)
- [x] https://github.com/nim-lang/Nim/commit/741285b335343ad61afc2d48778c52cd097d1249 Update osfiles.nim, make `moveFile` consider permission on *nix (#22719)

**Comment by tersec** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/24537

(this is apparently busted right now, situation unclear)
